### ISSUE TITLE
Returns 500 if query string includes certain special characters

### ISSUE THREAD

**Issue by lcyraphael** [ukparliament/parliament.uk-search-prototype#25]
The page returns an internal service error if the query string includes certain special characters, even when the Search API and Google CSE handle such characters.

Examples:
Works: $, ~ 
Doesn't work: £, €, ĕ 

My anecdotal evidence suggests characters outside of the range of ASCII character codes 0032-0126 return a 500. Definitely anything taking up more than 1 byte in UTF-8 encoding returns an error as well.

This might be fixed in search.rb (CGI.escape?)

**Comment by mattrayner** [comment]
We believe this has been fixed on DEVCI and should be pushed to live in our next release
